Feature: The sum of the even-valued fibonacci terms.

    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with and 1, 2 the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89.

    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.

    Scenario: Find the sum of even-valued terms of fibonacci before reaching the term four million
        Given a fibonacci sequence
        Then the first terms are
            | terms |
            | 1     |
            | 2     |
            | 3     |
            | 5     |
            | 8     |
            | 13    |
            | 21    |
            | 34    |
            | 55    |
            | 89    |
