[package]
name = "st_prime"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
cucumber = { version = "0.20.2" }
tokio    = { version = "1.37.0", features = ["full"] }

[[test]]
name    = "st_prime"
harness = false
