[package]
name = "largest_palindrome_product"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
cucumber = { version = "0.20.2" }
tokio    = { version = "1.37.0", features = ["full"] }

[[test]]
name    = "largest_palindrome_product"
harness = false
